spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
  application:
    name: RatingService
  config:
    import: optional:configserver:http://localhost:8085  
      
server:
  port: 9001
  
     
      
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true 
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8080/eureka
# 
 
okta:
  oauth2:
    issuer: https://dev-75985842.okta.com/oauth2/default      
    audience: api://default   